#!/bin/bash

set -e


# Start cron daemon
service cron start
service cron status

# Migrate database
echo ">>> Migrating database..."
python manage.py migrate

# Run server
echo ">>> Starting server..."
python manage.py runserver 0.0.0.0:8000

