#!/bin/bash

set -e


# Setting up cronjob...
echo ">>> Setting up cronjob..."
cp cronjobs/pollmarkets /etc/cron.hourly/pollmarkets || true # don't let script fail

# Migrate database
echo ">>> Migrating database..."
python manage.py migrate

# Run server
echo ">>> Starting server..."
python manage.py runserver 0.0.0.0:8000
