#!/bin/bash

set -e

echo "*********** BUILDING DOCKER IMAGE ***********"
docker-compose build

echo "*********** DEPLOYING ***********"
docker-compose up -d

echo "*********** WAITING 10 SECS ***********"
sleep 10

echo "*********** PRINTING CONTAINER LOGS ***********"


echo "*********** CHECKING DEPLOYMENT ***********"
curl -fkIL http://$TARGET_HOST:8000
