#!/bin/bash

set -e

openssl aes-256-cbc \
  -K $encrypted_537cba538591_key \
  -iv $encrypted_537cba538591_iv \
  -in .docker/web.env.enc \
  -out .docker/web.env \
  -d

openssl aes-256-cbc \
  -K $encrypted_537cba538591_key \
  -iv $encrypted_537cba538591_iv \
  -in docker/cron.env.enc \
  -out .docker/cron.env \
  -d
